//! Self-replication — spawning child automatons in new sandboxes.
//!
//! Process:
//! 1. Check child count limit (max 3)
//! 2. Create a new Conway sandbox
//! 3. Install runtime (Rust binary or Node.js)
//! 4. Write genesis config for child
//! 5. Propagate constitution (immutable)
//! 6. Fund child with initial credits
//! 7. Start child process

use crate::config::AutomatonConfig;
use crate::conway::ConwayClient;
use crate::state::Database;
use crate::types::{ChildRecord, GenesisConfig};
use anyhow::{bail, Result};
use chrono::Utc;
use std::sync::Arc;
use tokio::sync::Mutex;
use tracing::info;

/// Maximum children per parent agent.
const MAX_CHILDREN: u32 = 3;

/// Spawn a child automaton.
pub async fn spawn_child(
    config: &AutomatonConfig,
    conway: &ConwayClient,
    db: &Arc<Mutex<Database>>,
    genesis: GenesisConfig,
) -> Result<ChildRecord> {
    // 1. Check child limit
    let current_count = {
        let db_lock = db.lock().await;
        db_lock.active_children_count()?
    };

    if current_count >= config.max_children.min(MAX_CHILDREN) {
        bail!(
            "Child limit reached ({}/{}). Cannot spawn more.",
            current_count,
            config.max_children
        );
    }

    info!("Spawning child '{}' ...", genesis.name);

    // 2. Create new sandbox
    let sandbox_id = conway.create_sandbox(&genesis.name).await?;
    info!("Created sandbox: {}", sandbox_id);

    // 3. Install runtime in the child sandbox
    // For now we exec commands in the parent to set up the child
    // (real implementation would use the child sandbox's exec endpoint)
    let _install_script = format!(
        r#"
        # Install automaton runtime in child sandbox
        curl -fsSL https://conway.tech/automaton.sh | sh
        "#
    );
    // Note: In production, this would target the child sandbox
    info!("Child runtime installation initiated");

    // 4. Write genesis configuration
    let _child_config = AutomatonConfig {
        name: genesis.name.clone(),
        genesis_prompt: genesis.genesis_prompt.clone(),
        creator_address: String::new(),
        sandbox_id: sandbox_id.clone(),
        conway_api_url: config.conway_api_url.clone(),
        conway_api_key: String::new(), // Child provisions its own key
        parent_address: genesis.parent_address.clone(),
        ..AutomatonConfig::default()
    };

    info!("Genesis config written for child '{}'", genesis.name);

    // 5. Constitution propagation is handled by the install script
    // The constitution is immutable and inherited by all children

    // 6. Record the child
    let child = ChildRecord {
        id: ulid::Ulid::new().to_string(),
        name: genesis.name,
        sandbox_id,
        wallet_address: String::new(), // Generated by child on first run
        created_at: Utc::now(),
        status: "provisioning".into(),
    };

    {
        let db_lock = db.lock().await;
        db_lock.add_child(&child)?;
    }

    info!("Child '{}' spawned successfully (sandbox: {})", child.name, child.sandbox_id);

    Ok(child)
}
